"""Interactive setup for Hawk TUI."""

import os
import sys
from pathlib import Path

# Config file location (XDG standard)
CONFIG_DIR = Path.home() / ".config" / "hawk"
CONFIG_FILE = CONFIG_DIR / "config.toml"


def get_config_path() -> Path:
    """Return the config file path."""
    return CONFIG_FILE


def config_exists() -> bool:
    """Check if config file exists."""
    return CONFIG_FILE.exists()


def load_config() -> dict:
    """Load config from file, return empty dict if not found."""
    if not CONFIG_FILE.exists():
        return {}

    config = {}
    try:
        with open(CONFIG_FILE) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, value = line.split("=", 1)
                    key = key.strip()
                    value = value.strip().strip('"').strip("'")
                    config[key] = value
    except Exception:
        return {}

    return config


def save_config(config: dict) -> None:
    """Save config to file."""
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    with open(CONFIG_FILE, "w") as f:
        f.write("# Hawk TUI Configuration\n")
        f.write("# Generated by 'hawk init'\n\n")

        f.write("# Image Generation Backend\n")
        if "USE_LOCAL_IMAGE_GEN" in config:
            f.write(f'USE_LOCAL_IMAGE_GEN = "{config["USE_LOCAL_IMAGE_GEN"]}"\n')

        if "REPLICATE_API_TOKEN" in config:
            f.write(f'REPLICATE_API_TOKEN = "{config["REPLICATE_API_TOKEN"]}"\n')

        f.write("\n# Local Model Settings (if USE_LOCAL_IMAGE_GEN=true)\n")
        if "SD_MODEL" in config:
            f.write(f'SD_MODEL = "{config["SD_MODEL"]}"\n')
        if "SD_INFERENCE_STEPS" in config:
            f.write(f'SD_INFERENCE_STEPS = "{config["SD_INFERENCE_STEPS"]}"\n')
        if "SD_GUIDANCE_SCALE" in config:
            f.write(f'SD_GUIDANCE_SCALE = "{config["SD_GUIDANCE_SCALE"]}"\n')

        f.write("\n# Ollama Prompt Enhancement (optional)\n")
        if "USE_OLLAMA" in config:
            f.write(f'USE_OLLAMA = "{config["USE_OLLAMA"]}"\n')
        if "OLLAMA_MODEL" in config:
            f.write(f'OLLAMA_MODEL = "{config["OLLAMA_MODEL"]}"\n')

        f.write("\n# Content Directory (where images/videos are saved)\n")
        if "CONTENT_DIR" in config:
            f.write(f'CONTENT_DIR = "{config["CONTENT_DIR"]}"\n')


def print_banner():
    """Print setup banner."""
    print("\n" + "=" * 50)
    print("  HAWK TUI - Setup Wizard")
    print("  Terminal-based TikTok Video Creator")
    print("=" * 50 + "\n")


def prompt_choice(question: str, options: list[tuple[str, str]], default: int = 0) -> str:
    """Prompt user to choose from options. Returns the value."""
    print(f"\n{question}\n")
    for i, (label, _) in enumerate(options):
        marker = "[*]" if i == default else "[ ]"
        print(f"  {i + 1}. {marker} {label}")

    while True:
        try:
            choice = input(f"\nEnter choice (1-{len(options)}) [{default + 1}]: ").strip()
            if not choice:
                return options[default][1]
            idx = int(choice) - 1
            if 0 <= idx < len(options):
                return options[idx][1]
        except (ValueError, IndexError):
            pass
        print(f"Please enter a number between 1 and {len(options)}")


def prompt_input(question: str, default: str = "", secret: bool = False) -> str:
    """Prompt user for text input."""
    prompt_text = f"{question}"
    if default:
        prompt_text += f" [{default}]"
    prompt_text += ": "

    if secret:
        import getpass
        value = getpass.getpass(prompt_text)
    else:
        value = input(prompt_text)

    return value.strip() or default


def prompt_yes_no(question: str, default: bool = True) -> bool:
    """Prompt user for yes/no."""
    default_str = "Y/n" if default else "y/N"
    while True:
        response = input(f"{question} [{default_str}]: ").strip().lower()
        if not response:
            return default
        if response in ("y", "yes"):
            return True
        if response in ("n", "no"):
            return False
        print("Please enter 'y' or 'n'")


def run_setup():
    """Run interactive setup wizard."""
    print_banner()

    config = {}

    # Step 1: Choose backend
    print("Step 1: Image Generation Backend")
    print("-" * 35)

    backend = prompt_choice(
        "How do you want to generate images?",
        [
            ("Local (free, uses your GPU/CPU, ~6GB download)", "local"),
            ("Replicate API (cloud, requires API key, pay per image)", "replicate"),
        ],
        default=0
    )

    if backend == "local":
        config["USE_LOCAL_IMAGE_GEN"] = "true"

        # Choose model
        print("\n\nStep 2: Local Model Selection")
        print("-" * 30)

        model = prompt_choice(
            "Which model do you want to use?",
            [
                ("SDXL-Turbo (6GB, fast, good quality) - Recommended", "stabilityai/sdxl-turbo"),
                ("Flux Schnell (23GB, best quality, slower)", "black-forest-labs/FLUX.1-schnell"),
                ("SD 1.5 (4GB, classic, fast)", "runwayml/stable-diffusion-v1-5"),
            ],
            default=0
        )
        config["SD_MODEL"] = model

        # Set appropriate defaults for each model
        if "flux" in model.lower():
            config["SD_INFERENCE_STEPS"] = "4"
            config["SD_GUIDANCE_SCALE"] = "0.0"
        elif "turbo" in model.lower():
            config["SD_INFERENCE_STEPS"] = "8"
            config["SD_GUIDANCE_SCALE"] = "0.0"
        else:
            config["SD_INFERENCE_STEPS"] = "20"
            config["SD_GUIDANCE_SCALE"] = "7.5"

    else:
        config["USE_LOCAL_IMAGE_GEN"] = "false"

        print("\n\nStep 2: Replicate API Key")
        print("-" * 25)
        print("Get your API key from: https://replicate.com/account/api-tokens\n")

        api_key = prompt_input("Enter your Replicate API token", secret=True)
        if api_key:
            config["REPLICATE_API_TOKEN"] = api_key
        else:
            print("\nWarning: No API key provided. You'll need to set REPLICATE_API_TOKEN later.")

    # Step 3: Ollama (optional)
    print("\n\nStep 3: Prompt Enhancement (Optional)")
    print("-" * 37)
    print("Ollama can enhance your prompts with better descriptions.")
    print("Requires Ollama installed: brew install ollama\n")

    use_ollama = prompt_yes_no("Enable Ollama prompt enhancement?", default=False)
    config["USE_OLLAMA"] = "true" if use_ollama else "false"

    if use_ollama:
        model = prompt_input("Ollama model to use", default="llama3.2:latest")
        config["OLLAMA_MODEL"] = model

    # Step 4: Content directory
    print("\n\nStep 4: Content Directory")
    print("-" * 25)
    default_content = str(Path.home() / "hawk-content")
    print(f"Where should Hawk save generated images and videos?\n")

    content_dir = prompt_input("Content directory", default=default_content)
    config["CONTENT_DIR"] = content_dir

    # Save config
    print("\n\n" + "=" * 50)
    print("  Configuration Summary")
    print("=" * 50)

    for key, value in config.items():
        if "TOKEN" in key or "KEY" in key:
            display_val = value[:8] + "..." if len(value) > 8 else "***"
        else:
            display_val = value
        print(f"  {key}: {display_val}")

    print(f"\n  Config file: {CONFIG_FILE}")
    print("=" * 50)

    if prompt_yes_no("\nSave this configuration?", default=True):
        save_config(config)
        print(f"\n Config saved to {CONFIG_FILE}")

        # Create content directory
        content_path = Path(config.get("CONTENT_DIR", default_content))
        content_path.mkdir(parents=True, exist_ok=True)
        print(f" Content directory created: {content_path}")

        print("\n" + "=" * 50)
        print("  Setup complete! Run 'hawk' to start.")
        print("=" * 50 + "\n")
    else:
        print("\nSetup cancelled. No changes made.")


def show_config():
    """Show current configuration."""
    if not config_exists():
        print("No configuration found. Run 'hawk init' to set up.")
        return

    print(f"\nConfig file: {CONFIG_FILE}\n")
    print("-" * 40)

    config = load_config()
    for key, value in config.items():
        if "TOKEN" in key or "KEY" in key:
            display_val = value[:8] + "..." if len(value) > 8 else "***"
        else:
            display_val = value
        print(f"{key}: {display_val}")

    print("-" * 40)


if __name__ == "__main__":
    run_setup()
